import { randomBytes } from "node:crypto";

// Allowlist of supported, non-executable media. Executable/script formats are
// never accepted, and object keys are always generated by the server.
export const ALLOWED_MIME_TYPES: Record<string, string> = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/webp": "webp",
  "image/avif": "avif",
  "image/gif": "gif",
  "application/pdf": "pdf",
};

export const MAX_UPLOAD_BYTES = 10 * 1024 * 1024; // 10 MiB

export type MediaValidationResult =
  | { ok: true; extension: string }
  | { ok: false; error: string };

export function validateUpload(mimeType: string, sizeBytes: number): MediaValidationResult {
  const extension = ALLOWED_MIME_TYPES[mimeType];
  if (!extension) {
    return { ok: false, error: `Type de fichier non supporté : ${mimeType}.` };
  }
  if (sizeBytes <= 0 || sizeBytes > MAX_UPLOAD_BYTES) {
    return {
      ok: false,
      error: `Fichier trop volumineux (maximum ${Math.round(MAX_UPLOAD_BYTES / 1024 / 1024)} Mo).`,
    };
  }
  return { ok: true, extension };
}

/** Server-generated, collision-resistant object key. The client cannot choose it. */
export function generateObjectKey(mimeType: string): string {
  const extension = ALLOWED_MIME_TYPES[mimeType] ?? "bin";
  const now = new Date();
  const yyyy = now.getUTCFullYear();
  const mm = String(now.getUTCMonth() + 1).padStart(2, "0");
  const random = randomBytes(16).toString("hex");
  return `media/${yyyy}/${mm}/${random}.${extension}`;
}
